language: ruby
services:
  - postgresql
cache:
  - bundler
before_install:
  - nvm install --lts
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake assets:precompile
script:
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: TNeWbR9jvURqdRUJ8mWoPRWC93N56GdpNQyDuyxcgAXttm4s2MZ0D8mXn/HeuQbP+xmftzA0ho5K+b83fsGbpL6zNf//dh2P9p2/2iOZAlO06dXg0M0r4ZvO9TmYsH5zglWUO4rLQpISowWUI3S1P3rR+5ZZeVZTicJ7xz7Mx2Gjnf/a1bZg+ukir3vHXW0Ud7F3kICkrJu7l5WT4wERe/gZxrBrx4gxs5gP5Tp1aQEacm4gmHlOvMUyuhmIePFCKfQlu+OApIT8lVRgQfah3cRl31VeQq+X2zFYkKx7z072greedo79MeKnWAnxNDPttEJ8YmNmLpVqEnmNdbj49IaTS/EtgIfKBHk2UWxVjgNg8l5Pb4nBq5I0AwRakRLDw+GHuAZQgNXCe5aGMSj5t5CLxSDR4792t+Y/INJjmWCBQmGeXRE4qvNbOLX6kdLyckZtfiwrlBfDqOUNBOp5WCkEXOxgO6GI8Vpkpu1CvTGniqKf2fqCZA8oG8ixn/Yhkp9SZLeAyYN585p2vG/fpBPBGnYvO/V+B1RzE1xn18fQEoe/q2XBCZFe2qDqe1sQE1dOwzAc9LNhs1TBHvWmEpH1fAwv4nu4TRXM8BpSOy15R2Ki3USvQxS0SaePA167FK5ObT8PJsTtcvAbfKMaVi6zuRW6kAep/BI+HvPLRIs=
  app: bookaroo-deploy
  on:
    repo: stevej763/howdy-partners-bookaroo-new
    branch: main
  skip_cleanup: "true"
